export const ACTION_SET_NEWS_DATA = 'SET_NEWS_DATA';
export const ACTION_SET_VIDEO_DATA = 'SET_VIDEO_DATA';
export const ACTION_SET_LIVE_MATCH_DATA = 'SET_LIVE_MATCH_DATA';
export const ACTION_SET_COMPETITION_URL = 'SET_COMPETITION_URL';
export const ACTION_SET_COMPETITION_ID = 'SET_COMPETITION_ID';
export const ACTION_SET_TEAMS = 'SET_TEAMS';
export const ACTION_SET_PLAYER_PROFILE_URL = 'SET_PLAYER_PROFILE_URL';
export const ACTION_SET_LIVE_MATCH_INDEX = 'SET_LIVE_MATCH_INDEX';
