# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'cpl' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for cpl
  pod 'XCDYouTubeKit', '~> 2.5'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Google-Mobile-Ads-SDK'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

end
